__init__.py:
  NAME: "Home"
  ICON: "🏠"
  DESCRIPTION: "Welcome to my app!"

action_recognition:
  __init__.py:
    NAME: Action Recognition
    ICON: 🏋️
    DESCRIPTION: Perform action recognition using a classifier!
    TAG: 👁️ Computer Vision

image_generation:
  __init__.py:
    NAME: Image Generation
    ICON: 🎨
    DESCRIPTION: Generate pictures with AI!
    SIDEBAR: radio
    TAG: 🧠 Generative AI

  dall_e.py:
    NAME: DALL·E
    ICON: 🖼️
    DESCRIPTION: DALL·E model from OpenAI

  stable_diffusion.py:
    NAME: Stable Diffusion
    ICON: 🖼️
    DESCRIPTION: Stable Diffusion model from Stability AI

object_detection:
  __init__.py:
    NAME: Object Detection
    ICON: 🎯
    DESCRIPTION: Detect objects via your webcam!
    SIDEBAR: radio
    TAG: 👁️ Computer Vision

  face_landmarks.py:
    NAME: Face Mesh
    ICON: 👤
    DESCRIPTION: Face landmark detection
    TAG: 📍 Landmarks

  pose_landmarks.py:
    NAME: Pose Landmarks
    ICON: 🤸‍♂️
    DESCRIPTION: Body pose landmark detection
    TAG: 📍 Landmarks

  face_detection.py:
    NAME: Face Detection
    ICON: 👀
    DESCRIPTION: Detection of one or several faces
    TAG: 🔍 Detection

large_language_models:
  __init__.py:
    NAME: Large Language Models
    ICON: 💬
    DESCRIPTION: Chat with large language models!
    SIDEBAR: radio
    TAG: 🧠 Generative AI

  chatbot.py:
    NAME: Basic
    ICON: 👋
    DESCRIPTION: A regular chatbot.
    TAG: 🤖 Chatbots

  chatbot_rag.py:
    NAME: RAG
    ICON: 📄
    DESCRIPTION: A chatbot with RAG (retrieval augmented generation).
    TAG: 🤖 Chatbots

  chatbot_tools.py:
    NAME: Tools
    ICON: 🛠️
    DESCRIPTION: A chatbot augmented with tools (web access, code interpreter, etc.)
    TAG: 🤖 Chatbots

  summarize_web.py:
    NAME: Webpage summary
    ICON: 🌐
    DESCRIPTION: A model to synthetize to text content of a webpage.
    TAG: 🔄 Other